name: Build Releases

on:
  workflow_dispatch:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install requirements
      run: |
        sudo apt-get update
        sudo apt-get upgrade -y
        sudo apt-get install build-essential subversion git-core libncurses5-dev zlib1g-dev gawk flex quilt libssl-dev xsltproc libxml-parser-perl \
          mercurial bzr ecj cvs unzip lib32z1 lib32z1-dev lib32stdc++6 libstdc++6 libmpc-dev libgmp-dev tree liblua5.1-dev gcc-arm-none-eabi \
          gcc-arm-linux-gnueabi python3 -y

    - name: Clone Repository
      run: git clone https://github.com/v923z/micropython-ulab.git ulab
        
    - name: Build for RP2
      run: |
        cd ulab/build
        chmod +x rp2.sh
        ./rp2.sh
          
    - name: Upload result as release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "$GITHUB_WORKSPACE/micropython/ports/rp2/build-RPI_PICO/firmware.*"
#        body: ""
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: "RP2-Micropython"
        name: "RP2-Micropython"
  
